### ISSUE TITLE
Terms of Service at first log-in specify wrong institution

### ISSUE THREAD

**Issue by AndyBoze** [ndlib/planning#381]
curate production
Build: v2013.42 
Windows 7: Firefox

The Terms of Service document has a couple of minor punction errors, which I can mention later, but there's a reference to Penn State, which should be replaced by Notre Dame.
![pennstatetos](https://f.cloud.github.com/assets/5333250/1674932/ff4ade80-5d00-11e3-9d77-38a606881660.png)

**Comment by danhorst** [comment]
This issue has been resloved
